# Generated by Django 3.1.5 on 2021-01-19 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('plan_id', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='CustomPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(null=True)),
                ('plan_id', models.DecimalField(decimal_places=0, max_digits=4)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('energy', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('user_id', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('energy', models.DecimalField(decimal_places=0, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=1, max_digits=5)),
                ('carbohydrate', models.DecimalField(decimal_places=1, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
    ]
