# Generated by Django 2.2 on 2021-01-22 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_auto_20210122_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='food_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='user_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foundationfood',
            name='food_id',
            field=models.IntegerField(),
        ),
    ]
