# Generated by Django 2.2 on 2021-01-22 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0006_auto_20210122_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfood',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Food'),
        ),
        migrations.AlterField(
            model_name='customfood',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foundationfood',
            name='food_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.Food'),
        ),
    ]
