# Generated by Django 2.2 on 2021-01-24 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0013_auto_20210124_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodset',
            name='user_id',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='food_set_id',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='food_set_id',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='food_set_id',
        ),
        migrations.AlterField(
            model_name='basicplan',
            name='plan_id',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='basicplan',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='customplan',
            name='plan_id',
            field=models.DecimalField(decimal_places=0, max_digits=4),
        ),
        migrations.AlterField(
            model_name='customplan',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Component',
        ),
        migrations.DeleteModel(
            name='FoodSet',
        ),
        migrations.DeleteModel(
            name='Meal',
        ),
        migrations.DeleteModel(
            name='Recipe',
        ),
        migrations.DeleteModel(
            name='ShoppingList',
        ),
    ]
